### ISSUE TITLE
get balance error

### ISSUE THREAD

**Issue by annaapple15** [IrvKalb/Object-Oriented-Python-Code#10] opened 2024-08-29 19:34 UTC
When running Main_Bank_Version6.py, I have been unable to get an account balance. 

Here is what it is telling me:

What do you want to do? b

*** Get Balance ***
Traceback (most recent call last):
  File "c:\Users\annal\python_work\Object_oriented_python\Main_Bank_Version6.py", line 29, in <module>
    oBank.balance()
  File "c:\Users\annal\python_work\Object_oriented_python\Bank.py", line 64, in balance     
    theBalance = oAccount.getBalance()
                 ^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'getBalance'

I am new to coding and have been teaching myself through textbooks, I followed this code all the way from start to finish, through every version, and even double checked with yours on here. How do I fix this to get it to run? Forgive me if I am using this issues application wrong also, I am new to github.

**Comment by IrvKalb** [comment] 2024-08-29 22:53
Hi,

Thanks for your message.  I'm not sure what is causing this error, because when I try the code, it works fine.  

First, did you download the code from this GitHub repository?  If not, I would recommend that you do so.  I have fixed a number of small bugs in the code (although none in this area) that you may run into in the future.  I just tried the version of the code from this repository and it works fine for me.  

I'd be happy to look at this.  Could you please make a zip file out this project folder (BankOOP6_UsingExceptions) and send it to me directly:  Irv at furrypants dot com     

I'll take a look at the code you have and figure out what's going wrong.  (It sounds like the Bank object was not being created correctly - or the code of the Bank class was corrupted.)

One question:  When you tried running and got this error, had you created any accounts yet?

Thanks,

Irv

**Comment by IrvKalb** [comment] 2024-09-03 19:02
Please let me know if this is still an issue.  Please contact me if you are still having any problems with this code.

If I don't hear back from you in a few days, I will close this issue.

Irv

**Comment by IrvKalb** [comment] 2024-09-05 16:45
I have not heard back from you.  Since I am not able to reproduce the problem that you wrote about, I am closing this issue.

**Closed as completed by IrvKalb** 2024-09-05 16:45 UTC
